// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJLF-VWxSy1aLzhDAkS_0qf4UhHO3nt40',
    appId: '1:33688191487:web:fd981684965d359757e7ca',
    messagingSenderId: '33688191487',
    projectId: 'ecobin-back-end',
    authDomain: 'ecobin-back-end.firebaseapp.com',
    storageBucket: 'ecobin-back-end.appspot.com',
    measurementId: 'G-4KEXNQ0VJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_6aZ7nmZsgWJqXWH9Bc8_FL8FYoq1424',
    appId: '1:33688191487:android:c53ab6973548771057e7ca',
    messagingSenderId: '33688191487',
    projectId: 'ecobin-back-end',
    storageBucket: 'ecobin-back-end.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ZOQYxSA-W5G7u8L8SqaxFOIwU9ZTBTM',
    appId: '1:33688191487:ios:9ef7a3382618fe6b57e7ca',
    messagingSenderId: '33688191487',
    projectId: 'ecobin-back-end',
    storageBucket: 'ecobin-back-end.appspot.com',
    iosBundleId: 'com.example.ecoBinOriginal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ZOQYxSA-W5G7u8L8SqaxFOIwU9ZTBTM',
    appId: '1:33688191487:ios:9ef7a3382618fe6b57e7ca',
    messagingSenderId: '33688191487',
    projectId: 'ecobin-back-end',
    storageBucket: 'ecobin-back-end.appspot.com',
    iosBundleId: 'com.example.ecoBinOriginal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJLF-VWxSy1aLzhDAkS_0qf4UhHO3nt40',
    appId: '1:33688191487:web:05ee5266032c248157e7ca',
    messagingSenderId: '33688191487',
    projectId: 'ecobin-back-end',
    authDomain: 'ecobin-back-end.firebaseapp.com',
    storageBucket: 'ecobin-back-end.appspot.com',
    measurementId: 'G-33KVS4NFFD',
  );
}
